// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nzkssrxqxmrasxjfipri.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im56a3NzcnhxeG1yYXN4amZpcHJpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwMzIxNjcsImV4cCI6MjA2NjYwODE2N30._etlB8VWsNYK2Wyz7OZlLpesMYB2q-OGnxfd48XHqCo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);